obstacle_layer:
  observation_sources: pointcloud
  pointcloud: {data_type: PointCloud2,
               topic: /slamcore/local_point_cloud,
               marking: true,
               clearing: true}
